[build]
  command = ""
  publish = "."
  environment = { SECRETS_SCAN_OMIT_PATHS = "assets/js/index.inline3.js" }

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Função agendada para processar lembretes (executa a cada minuto)
[[scheduled.functions]]
  function = "process-reminders"
  cron = "*/1 * * * *"
